### ISSUE TITLE
Window not closing when pressing close or esc

### ISSUE THREAD

**Issue by suppergerrie2** [schematical/chaostrainer-public#1]
Version: 0.0.1
OS: Windows 10

After loading a level (I was using Lava from the save_data folder) I pressed D which opened a window showing the path.
This window has a close button which doesn't work (also the clear button doesn't seem to do anything)

![screenshotchaostrainer](https://user-images.githubusercontent.com/15769860/46368425-796b7880-c680-11e8-869a-568b8a3649bf.png)

**Comment by schematical** [comment]
Try "Ctl+D" to open and close.
I will work on adding that close button functionality

**Comment by schematical** [comment]
Fixed(Except the Ctl part) and the close button should work. Also it should render over all other screens
