### ISSUE TITLE
Setting menu on trainingroom selection menu not working

### ISSUE THREAD

**Issue by suppergerrie2** [schematical/chaostrainer-public#10]
Version 0.0.3
OS: Windows 10

On the training room selection menu you can press "settings" next to "edit level". This opens a menu but you can't click on anything.
![image](https://user-images.githubusercontent.com/15769860/46492834-004e5b80-c80f-11e8-82c4-00488000e1ec.png)

**Comment by schematical** [comment]
Yeah I need t rethink this. I will prob remove that button for the moment

**Comment by suppergerrie2** [comment]
Still same problem in 0.0.5

**Comment by suppergerrie2** [comment]
Still in 0.0.6

**Comment by suppergerrie2** [comment]
Button is gone so this is no longer an issue
