### ISSUE TITLE
Random word in top menu

### ISSUE THREAD

**Issue by suppergerrie2** [schematical/chaostrainer-public#11]
Version: 0.0.3
OS: Windows 10

When in a training room the top bar says: Time Scale: 1 Max Bots: 40 High Score 19 Curr Generation: 100 **Spawned**.
Nothing is displayed after spawned, I don't know if it should display a number or if it shouldn't say spawned at all.

(The numbers are chosen randomly :P)

**Comment by schematical** [comment]
I thing that is a screen res issue. I am struggling to get fonts to fit right across resolutions.

**Comment by suppergerrie2** [comment]
It has a lot of space around it, so shouldn't really be a problem

**Comment by suppergerrie2** [comment]
![image](https://user-images.githubusercontent.com/15769860/46740762-e21bac00-cca3-11e8-9937-f4389e1c556b.png)

still in 0.0.5

**Comment by suppergerrie2** [comment]
This is fixed for me in 0.0.6
