### ISSUE TITLE
Neat options for mutation no longer filled in

### ISSUE THREAD

**Issue by suppergerrie2** [schematical/chaostrainer-public#14]
Version: 0.0.4
OS: Windows 10

When opening the brain-maker settings all of the chance inputs are empty:
![image](https://user-images.githubusercontent.com/15769860/46569358-01d56c00-c954-11e8-92f0-bebea1db451d.png)

**Comment by schematical** [comment]
Found that bug, fixed it. Should be fixed in the next build

**Comment by suppergerrie2** [comment]
Fixed!
