### ISSUE TITLE
Bots don't spawn after leaving the level and going back

### ISSUE THREAD

**Issue by suppergerrie2** [schematical/chaostrainer-public#6]
Version: 0.0.1
OS: Windows 10

Steps to reproduce:
  1. Load a level with a spawner
  2. Notice the bots spawning
  3. Leave the level
  4. Load the level again
  5. No bots will spawn no matter the max bots setting

**Comment by schematical** [comment]
Yeah this is a bug I am aware of. Something breaks when destroying the level. This is definitely a high priority.
