### ISSUE TITLE
Decreasing max bot count not working correctly

### ISSUE THREAD

**Issue by suppergerrie2** [schematical/chaostrainer-public#7]
Version: 0.0.1
OS: Windows 10

When pressing q the max bot count will reset to 0, pressing e after that has no effect.
Temp fix: Press q twice to get to 5 and you can increase the count after that

Steps to reproduce:
  1. Open level
  2. Press e (To make sure you aren't at 5)
  3. Press q (Notice the bot count dropping to 0)
  4. Press e (Notice nothing happening)
  5. Press q (Bot count now 5)

**Comment by schematical** [comment]
```
  if (
            Input.GetKeyDown(KeyCode.E)
        )
        {
            //Increase count
            if(GameManager.instance.fitnessManager.maxBotCount > 80){
                GameManager.instance.fitnessManager.maxBotCount = 160;
                return;
            }
            GameManager.instance.fitnessManager.maxBotCount *= 2;
        }

        if(
            Input.GetKeyDown(KeyCode.Q)
        ){
            //Decrease count
            if (GameManager.instance.fitnessManager.maxBotCount < 10)
            {
                GameManager.instance.fitnessManager.maxBotCount = 5;
                return;
            }
            GameManager.instance.fitnessManager.maxBotCount *= (int).5f;
        }
```
This is pretty much the exact code... I must be missing something

**Comment by schematical** [comment]
Also I just upped the count as per your request :)

**Comment by schematical** [comment]
I can replicate it now. Should be easy to find a fix

**Comment by suppergerrie2** [comment]
This line is the problem I think:
`
GameManager.instance.fitnessManager.maxBotCount *= (int).5f;
`

.You cast .5 to an integer, which will become 0, and something*0 is always 0.

**Comment by schematical** [comment]
This should be fixed now
